$(document).ready(function() {    

const fortunes = [
    'A big fortune will descend upon you this year.',
    'A chance meeting opens new doors to success and friendship.',
    'A dream you have will come true.',
    'A friend asks only for your time not your money.',
    'A good way to keep healthy is to eat more Chinese food.',
    'A journey of a thousand miles begins with a single step.',
    'A letter of great importance may reach you any day now.',
    'A lifetime of happiness is in store for you.',
    'A man is born to live and not prepare to live.',
    'A merry heart does good like a medicine.',
    'A new business venture is on the horizon.',
    'A new voyage will fill your life with untold memories.',
    'A smile is your passport into the hearts of others.',
    'A stranger, is a friend you have not spoken to yet.',
    'A very attractive person has a message for you.',
    'Adversity is the parent of virtue.',
    'All progress occurs because people dare to be different.',
    'All your fingers can\'t be of the same length.',
    'An upward movement initiated in time can counteract fate.',
    'Back away from individuals who are impulsive.',
    'Be tactful; overlook your own opportunity.',
    'Before trying to please others think of what makes you happy.',
    'Change can hurt, but it leads a path to something better.',
    'Conquer your fears or they will conquer you.',
    'Determination is the wake-up call to the human will.',
    'Do not fear what you don\'t know',
    'Do you believe? Endurance and persistence will be rewarded.',
    'Don\'t pursue happiness - create it.',
    'Elegant surroundings will soon be yours.',
    'Emotion is energy in motion.',
    'Enjoy the good luck a companion brings you.',
    'Enjoyed the meal? Buy one to go too.',
    'Every day is a new day. But tomorrow is never promised.',
    'Everyone agrees. You are the best.',
    'Everything happens for a reason.',
    'Express yourself: Don\'t hold back!',
    'Finish your work on hand don\'t be greedy.',
    'For success today look first to yourself.',
    'Fortune favors the brave.',
    'Good health will be yours for a long time.',
    'Good news from afar may bring you a welcome visitor.',
    'Happiness comes from a good life.',
    'Happiness is an activity.',
    'Happiness is often a rebound from hard work.',
    'Hard work pays off in the future, laziness pays off now.',
    'He who slithers among the ground is not always a foe.',
    'Hone your competitive instincts.',
    'Human evolution: “wider freeway" but narrower viewpoints.',
    'If winter comes, can spring be far behind?',
    'If you feel you are right, stand firmly by your convictions.',
    'If you have something good in your life, don\'t let it go!',
    'If you have something worth fighting for, then fight for it.',
    'If you wish to know the mind of a man, listen to his words',
    'If you\'re happy, you\'re successful.',
    'If your desires are not extravagant, they will be rewarded.',
    'Impossible is a word only to be found in the dictionary of fools.',
    'In case of fire, keep calm, pay bill and run.',
    'Instead of worrying and agonizing, move ahead constructively.',
    'Integrity is doing the right thing, even if nobody is watching.',
    'Integrity is the essence of everything successful.',
    'It is now, and in this world, that we must live.',
    'It never pays to kick a skunk.',
    'It\'s better to be alone sometimes.',
    'Jealousy doesn\'t open doors, it closes them!',
    'Joys are often the shadows, cast by sorrows.',
    'Keep it simple. The more you say, the less people remember.',
    'Keep your eye out for someone special.',
    'Land is always on the mind of a flying bird.',
    'Let the deeds speak.',
    'Love can last a lifetime, if you want it to.',
    'Love is as necessary to human beings as food and shelter.',
    'Meeting adversity well is the source of your strength.',
    'Never give up. Always find a reason to keep trying.',
    'Never give up. You\'re not a failure if you don\'t give up.',
    'Never underestimate the power of the human touch.',
    'Next full moon brings an enchanting evening.',
    'Not all closed eye is sleeping nor open eye is seeing.',
    'Nothing astonishes men so much as common sense and plain dealing.',
    'Nothing seems impossible to you.',
    'Now is the time to try something new.',
    'Our deeds determine us, as much as we determine our deeds.',
    'Patience is a virtue, unless its against a brick wall.',
    'Patience is bitter, but its fruit is sweet.',
    'People are naturally attracted to you.',
    'Poverty is no disgrace.',
    'Prosperity makes friends and adversity tries them.',
    'Rivers need springs.',
    'Serious trouble will bypass you.',
    'Sometimes you just need to lay on the floor.',
    'Stay true to those who would do the same for you.',
    'Stop wishing. Start doing.',
    'The greatest risk is not taking one.',
    'The man on the top of the mountain did not fall there.',
    'The man or woman you desire feels the same about you.',
    'The object of your desire comes closer.',
    'The only certainty is that nothing is certain.',
    'The time is always right to do what is right.',
    'The world is always ready to receive talent with open arms.',
    'There are no limitations to the mind except those we acknowledge.',
    'There is no greater pleasure than seeing your loved ones prosper.',
    'There will be a happy romance for you shortly.',
    'To be old and wise, you must first be young and stupid.',
    'We can\'t help everyone. But everyone can help someone.',
    'Wealth awaits you very soon.',
    'Welcome the change coming into your life.',
    'When fear hurts you, conquer it and defeat it!',
    'When hungry, order more Chinese food.',
    'When you look down, all you see is dirt, so keep looking up.',
    'Whenever possible, keep it simple.',
    'You are a lover of words; One day you will write a book.',
    'You are a person of culture.',
    'You are extremely loved. Don\'t worry :)',
    'You are the controller of your destiny.',
    'You are very talented in many ways.',
    'You believe in the goodness of mankind.',
    'You can make your own happiness.',
    'You can open doors with your charm and patience.',
    'You cannot become rich except by enriching others.',
    'You cannot love life until you live the life you love.',
    'You have a deep appreciation of the arts and music.',
    'You have a deep interest in all that is artistic.',
    'You have an unusual equipment for success, use it properly.',
    'You learn from your mistakes... You will learn a lot today.',
    'You must try, or hate yourself for not trying.',
    'You try hard, never to fail. You don\'t, never to win.',
    'You will always be surrounded by true friends',
    'You will be successful in love.',
    'You will become better acquainted with a coworker.',
    'You will become great if you believe in yourself.',
    'You will conquer obstacles to achieve success.',
    'You will have a long and wealthy life.',
    'You will have a pleasant surprise',
    'You will have unexpected great good luck.',
    'You will make heads turn.',
    'You will make many changes before settling down happily.',
    'You will marry your lover.',
    'You will soon be honored by someone you respect.',
    'You will soon embark on a business venture.',
    'You will soon witness a miracle.',
    'You will take a pleasant journey to a place far away.',
    'You will travel to many exotic places in your lifetime.',
    'Your ability for accomplishment will follow with success.',
    'Your emotional nature is strong and sensitive.',
    'Your fondest dream will come true within this year.',
    'Your fortune is as sweet as a cookie.',
    'Your golden opportunity is coming shortly.',
    'Your happiness is intertwined with your outlook on life.',
    'Your high-minded principles spell success.',
    'Your life will be filled with magical moments.',
    'Your smile brings happiness to everyone you meet.'
];

document.getElementById("clicker").addEventListener("click", flipFortune);
function flipFortune() {
    const newFortune = Math.floor(Math.random() * fortunes.length);
    document.getElementById('fortuneBox').innerHTML = fortunes[newFortune];
}

document.getElementById("tweeter").addEventListener("click", tweet);
function tweet() {
    const quote = document.getElementById('fortuneBox').innerHTML;
    window.open(
      "https://twitter.com/intent/tweet?text=" + quote;
    );
}
